### ISSUE TITLE
Error when updating vortex

### ISSUE THREAD

**Issue by mamasch19** [JourneyOver/chocolatey-packages#70] opened 2023-09-01 07:35 UTC
Title says it all, when trying to update vortex from 1.8.0 to the latest version (1.9.4), installation failed.

Here's the debug log: [GitHub Gist](https://gist.github.com/mamasch19/3b483c2751f2d1dda9d16159cd9e64e2)

**Comment by JourneyOver** [comment] 2023-09-01 15:53
I'll take a look when I can but you also didn't fill out the actual bug report template at all, and my stance is usually if someone doesn't fill out the template then it's usually an immidiate close without anything else being looked into..

Try to run the update one more time and see if it outputs the same error message if you will, as so far you have been the only one to have this issue from what I can tell, but I'll still take a look into things when I can get a chance.

**Comment by JourneyOver** [comment] 2023-09-20 18:16
Well so far I have not been able to reproduce this issue on multiple different machines.. I think you just had a hiccup or something on your side that caused this issue.

I'll leave this open for now, in case anyone else ends up having this issue they can come and report it here instead of opening a new issue.. but since I've been unable to reproduce this issue on multiple machines this issue will eventually be closed.

**Comment by mamasch19** [comment] 2023-09-21 04:52
Sorry, but I didn't notice there was a report template. I used the link in README.md which brought me straight to a new empty issue. Maybe consider changing it to [this](https://github.com/JourneyOver/chocolatey-packages/issues/new/choose).
Here's some more info:

**Describe the bug**
When I try to update vortex to the latest version, chocolatey fails with the error "Cannot process argument transformation on parameter 'file'. Cannot convert value to type System.String."

**To Reproduce**
On my machine: Just update vortex to the latest version `choco upgrade vortex -y`

I testet some configurations but I was unable to reproduce the error myself on another machine (I got another error from the installer itself).

**Expected behavior**
It just updates without any errors.

**Desktop (please complete the following information):**
- OS: Windows 10
- Chocolatey version: v2.2.2, but it happened on other versions before that too
- Package version: v1.8.0 >> 1.9.4

**Chocolatey Install/Uninstall log**
see above

**Additional context**
I also testet it in a Windows 11 Sandbox and a Windows 10 VM. STill unable to reproduce.
I think for now I'll just update Vortex manually and via chocolatey with the `-n` parameter. 
If I find out anything else, I'll let you know.

**Comment by KucharczykL** [comment] 2023-11-06 07:50
I was also running into this issue. Apparently the problem is this part:

```powershell
$fileLocation = Get-Item "$toolsDir\*.exe"

$packageArgs = @{
  packageName    = $packageName
  fileType       = 'exe'
  file           = $fileLocation
  silentArgs     = "/S"
  validExitCodes = @(0)
}
```

`$fileLocation = Get-Item "$toolsDir\*.exe"` is returning a list of items instead of the expected single item. To fix it, I've added `| Select-Object -First 1` to the end of it:

```powershell
$fileLocation = Get-Item "$toolsDir\*.exe" | Select-Object -First 1
```

I'm not experienced with Powershell so take anything I say with a grain of salt, but this has fixed my issue.

**Comment by mamasch19** [comment] 2023-11-07 00:11
Yup, I recently discovered a similar solution on my end too, just didn't get around to updating here. I just deleted the other matching files from the directory and that worked for me. 
But now I get a different error from the vortex installer itself every time I try to update: 
![image](https://github.com/JourneyOver/chocolatey-packages/assets/51797687/64641b84-1d6e-4c15-810d-1fc72f75f3c1)
(_translates to_: The old application files could not be uninstalled. Please try running the installer again.: 2)

But I guess that's an issue on vortex's side and has nothing to do with the package itself...

**Comment by JourneyOver** [comment] 2023-11-07 01:05
The thing is this:
> I've added | Select-Object -First 1 to the end of it

shouldn't matter, as there should only be one thing being returned in the list anyways and that would be the one and only exe file in the `$toolsDir` which would be the latest setup exe file for vortex. Example being with the latest version as of current it should only be returning `vortex-setup-1.9.7.exe` and literally no other files for the `$fileLocation = Get-Item "$toolsDir\*.exe"` and then after the install it deletes said exe file.

I've also been unable to reproduce this on my end still as well nor has the automated package testing on the chocolatey site.

**Comment by KucharczykL** [comment] 2023-11-07 09:37
Unfortunately I can't help there because the folder, as you said, now contains only a single EXE file. But it seems that in the past somehow another EXE file made its way there during regular Chocolatey usage that is not caught by testing.

**Comment by JourneyOver** [comment] 2024-03-16 16:08
This package is being taken over by @pauby as noted in https://github.com/chocolatey-community/chocolatey-package-requests/issues/1511 so I'm going to go ahead and close this issue.

**Closed as completed by JourneyOver** 2024-03-16 16:08 UTC
Labels: bug
